name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Extract project name and build Docker image
    #     run: |
    #       repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
    #       docker build . --file Dockerfile --tag "$repo_name:$(date +%s)"
    # steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/my-project:latest
          repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          tag="$repo_name:$(date +%s)"
          docker build . --file Dockerfile --tag "$tag"

      # Push the Docker image
      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/$tag
