name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image with a dynamic tag
      - name: Build the Docker image
        run: |
          repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          tag="ghcr.io/${{ github.repository_owner }}/$repo_name:$(date +%Y%m%d%H%M%S)"
          echo "Built image with tag: $tag"
          docker build . --file Dockerfile --tag "$tag"
          echo "tag=$tag" >> $GITHUB_ENV

      # Push the Docker image
      - name: Push the Docker image
        run: |
          docker push ${{ env.tag }}
